WIP: Initial CLE integration to a CLEImage class
InsightSoftwareConsortium/ITKCLEsperanto pull request #21
Opened 2022-08-23 15:20 UTC by aaron-bray

2022-08-23 15:57 UTC, thewtex commented on include/itkCLEDataManager.h
> + * \ingroup ITKCLE
CLEsperanto

2022-08-23 15:57 UTC, thewtex commented on include/itkCLEDataManager.h
> +  using Self = CLEDataManager;
`Self` should be `SelfTemplate`

2022-08-23 15:57 UTC, thewtex commented on include/itkCLEDataManager.h
> +  }
Move to an `Image` specific class: `itk::CLEImageDataManager`.

2022-08-23 15:57 UTC, thewtex commented on include/itkCLEDataManager.h
> +  //}
We want to exercise these in the test:

```
instance->SetGPUBufferDirty();
instance->Update();
instance->SetCPUBufferDirty();
instance->Update();
```

2022-08-23 15:57 UTC, thewtex commented on include/itkCLEDataManager.h
> +  WeakPointer<CLEImage<TPixel, VDim>> m_Image; // WeakPointer has to be used here
-> Image specific class

2022-08-23 15:57 UTC, thewtex commented on include/itkCLEDataManager.h
> +  std::mutex m_Mutex;
Remove if possible

2022-08-23 15:57 UTC, thewtex commented on include/itkCLEDataManager.h
> +  cle::Clesperanto cle;
`static`  (at least for now). CLContextManager that holds a static singleton (can create an in issue if needed for the next PR.

2022-08-23 15:57 UTC, thewtex commented on include/itkCLEDataManager.hxx
> +template <typename TPixel, unsigned int VDim>
`VDim` -> `VDimension`

2022-08-23 15:57 UTC, thewtex commented on include/itkCLEImage.h
> +    //m_DataManager->UpdateCPUBuffer();
todo, etc

2022-08-23 15:57 UTC, thewtex commented on include/itkCLEImage.h
> +};
Check into `itk.Image.{h,hxx}`: see if it does not have any of this content. If so, we may not need it.

2022-08-23 15:57 UTC, thewtex commented on test/itkCLEImageTest.cxx
> +using ItkImage1f = itk::CLEImage<float, 2>;
inside the function

2022-08-23 15:57 UTC, thewtex commented on test/itkCLEImageTest.cxx
> +  ItkImage1f::Pointer srcA, srcB;
Separate lines.

```
using ImageType = itk::CLEImage<float, 2>;
auto srcA = ImageType::New();
auto srcB = ImageType::New();

2022-08-23 15:57 UTC, thewtex commented on test/itkCLEImageTest.cxx
> +  srcA->FillBuffer(1.0f);
GetPixel
SetPixel

2022-08-23 15:57 UTC, thewtex commented on test/itkCLEImageTest.cxx
> +  srcB->UpdateBuffers();
Previous comment

2022-08-23 15:57 UTC, thewtex commented on test/itkCLEImageTest.cxx
> +    return EXIT_FAILURE;
itkTestingMacros.h

2022-08-24 07:59 UTC, aktech commented
The GPU tests didn't run because it seems the credentials you have in Cirun doesn't have permissions for the given AMI:

See error here: https://github.com/InsightSoftwareConsortium/ITKCLEsperanto/pull/21/checks?check_run_id=7986383145

2022-08-24 13:42 UTC, thewtex requested changes
Good progress

2022-08-24 13:42 UTC, thewtex commented on example/ImageReadWrite.cxx
> +  auto reader = ReaderType::New();
Better to use `itk::ReadImage`, `itk::WriteImage`:

https://examples.itk.org/src/io/imagebase/readanimage/documentation

https://examples.itk.org/src/io/imagebase/writeanimage/documentation

2022-08-24 13:42 UTC, thewtex commented on include/itkCLEContextManager.h
> +class CLEContextManager : public LightObject
:+1:

2022-08-24 13:42 UTC, thewtex commented on include/itkCLEDataManager.hxx
> +  //os << indent << "m_CPUBuffer: " << m_CPUBuffer << std::endl;
uncomment

We can exercise these and more with

```
ITK_EXERCISE_BASIC_OBJECT_METHODS
```

from *itkTestingMacros.h*.

2022-08-24 13:42 UTC, thewtex commented on include/itkCLEImageDataManager.hxx
> +    itk::ImageRegionConstIterator<CLEImage<TPixel, VImageDimension>> itr(m_Image, m_Image->GetLargestPossibleRegion());
Largest -> Buffered

2022-08-26 16:44 UTC, thewtex commented
> The GPU tests didn't run because it seems the credentials you have in Cirun doesn't have permissions for the given AMI:

See error here: https://github.com/InsightSoftwareConsortium/ITKCLEsperanto/pull/21/checks?check_run_id=7986383145

@aktech thanks for the note!

@tbirdso could you please take a look?

2022-08-26 17:17 UTC, thewtex requested changes
Additional todos:

- [ ] test `Graft`, as with the [itkImageTest](https://github.com/InsightSoftwareConsortium/ITK/blob/05e9b3a16b52e9f34609a07b70c53f663468ab76/Modules/Core/Common/test/itkImageTest.cxx#L229-L235)
- [x] test equality after modifications [with the comparison image filter](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples/blob/ffdabca2f41e91a062b6b616f300f55ef088eddc/src/ImageCompareCommand.cxx#L284-L293) 
```
  using ComparisonFilterType = ComparisonImageFilter< CLEIImageType,
CLEImageType >;
```
- [ ] Addresss inline comments
- [ ] CI tests passing across platforms

2022-08-29 14:13 UTC, thewtex requested changes

2022-08-29 14:13 UTC, thewtex commented on include/itkCLEDataManager.hxx
> +  //os << indent << "m_GPUBuffer: " << m_GPUBuffer << std::endl;
Add

2022-08-29 14:13 UTC, thewtex commented on include/itkCLEImageDataManager.hxx
> +    std::cout << "I am pulling from the GPU\n";
Use `itkDebugMacro`, then set `DebugOn` in the test.

2022-08-29 14:13 UTC, thewtex commented on include/itkCLEImageDataManager.hxx
> +    std::cout << "I am pushing to the GPU\n";
Use `itkDebugMacro`, then set `DebugOn` in the test.

2022-08-29 14:13 UTC, thewtex commented on test/itkCLEImageTest.cxx
> +  ITK_EXERCISE_BASIC_OBJECT_METHODS(cleImage, CLEImage, Image)
:+1:

2022-08-29 14:13 UTC, thewtex commented on test/itkCLEImageTest.cxx
> +  if (Compare<ImageType>(srcA,srcB))
:+1:

2022-08-29 17:26 UTC, thewtex commented on CMakeLists.txt
> +add_subdirectory(example)
This is failing CI, does not appear to be a usable example.

Let's remove for now, investigate adding Jupyter notebooks later.

2022-08-29 18:42 UTC, thewtex requested changes

2022-08-29 18:42 UTC, thewtex commented on include/itkCLEImage.h
> +  }
Add `PrintSelf`.

2022-08-29 18:42 UTC, thewtex commented on include/itkCLEImage.h
> +  CLEDataManager<TPixel,VImageDimension>*
Use the typedef.

2022-08-29 18:42 UTC, thewtex commented on include/itkCLEImage.h
> +  }
same as base -- remove

2022-08-29 18:42 UTC, thewtex commented on include/itkCLEImage.h
> +  }
same as base -- remove

2022-08-29 18:42 UTC, thewtex commented on include/itkCLEImage.h
> +  using Superclass::Graft;
move above `Graft` on line 208

2022-08-29 18:42 UTC, thewtex commented on include/itkCLEImage.hxx
> +  m_DataManager = CLEImageDataManager<TPixel, VImageDimension>::New();
use typedef

2022-08-29 18:42 UTC, thewtex commented on include/itkCLEImageDataManager.hxx
> +  auto size = m_Image->GetLargestPossibleRegion().GetSize();
`BufferedRegion`

2022-08-29 18:42 UTC, thewtex commented on include/itkCLEDataManager.h
> +  cle::Object m_GPUBuffer;
-> `unique_ptr<cle::Object>` or `cli::Object *`

2022-08-29 18:42 UTC, thewtex commented on test/itkCLEImageTest.cxx
> +  srcB->SetPixel(idx, 7.0f);
Test `GetPixel`

2022-08-29 18:42 UTC, thewtex commented on test/itkCLEImageTest.cxx
> +  // Testing GetNeighborhoodAccessor
Remove

2022-08-30 18:30 UTC, thewtex commented on test/itkCLEImageTest.cxx
> +  ITK_TEST_EXPECT_EQUAL(A, B);
In these tests, `B` should explicitly be `12.0f` in the case, etc. `A` and `B` could both be `0.0` if setting the values failed and the test would still pass.

2022-08-30 19:24 UTC, thewtex commented on include/itkCLEImageDataManager.hxx
> +#define itkGPUImageDataManager_hxx
update macro name

2022-08-31 18:02 UTC, thewtex approved these changes

2022-08-31 18:53 UTC, merged